# Generated by Django 5.2.8 on 2026-01-19 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=100)),
                ('course', models.CharField(default='BIT', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Teachername', models.CharField(max_length=100)),
                ('department', models.CharField(default='IT', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teachername', models.CharField(max_length=100)),
                ('assigned_class', models.CharField(default='AI', max_length=100)),
                ('subject_name', models.CharField(default='Python', max_length=100)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.teacher')),
            ],
        ),
    ]
