# Generated by Django 5.2.8 on 2026-02-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
