# Generated by Django 5.2.8 on 2026-01-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Student',
        ),
    ]
